"""Add all missing fields to PlagiatMatch

Revision ID: 0041373c2ee1
Revises: 253eeb4731a1
Create Date: 2025-12-15 11:43:06.861440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041373c2ee1'
down_revision = '253eeb4731a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('matched_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('original_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('y')
        batch_op.drop_column('x')
        batch_op.drop_column('original_text')
        batch_op.drop_column('matched_text')
        batch_op.drop_column('url')
        batch_op.drop_column('score')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
