"""Add fields to PlagiatMatch

Revision ID: 253eeb4731a1
Revises: 
Create Date: 2025-12-15 11:40:22.578485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253eeb4731a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagiat_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plagiat_analyses_rapport'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rapports', ['rapport_id'], ['id'])

    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similarity', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_plagiat_matches_analysis'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plagiat_analyses', ['analysis_id'], ['id'])

    with op.batch_alter_table('rapports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rapports_auteur'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['auteur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rapports_auteur'), 'users', ['auteur_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plagiat_matches_analysis'), 'plagiat_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('similarity')

    with op.batch_alter_table('plagiat_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plagiat_analyses_rapport'), 'rapports', ['rapport_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
