"""Add all missing fields to PlagiatMatch

Revision ID: 91574cce2af4
Revises: 0041373c2ee1
Create Date: 2025-12-15 12:21:10.047907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91574cce2af4'
down_revision = '0041373c2ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagiat_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chunks_analyzed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chunks_with_matches', sa.Integer(), nullable=True))

    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plagiat_matches', schema=None) as batch_op:
        batch_op.drop_column('chunk_index')

    with op.batch_alter_table('plagiat_analyses', schema=None) as batch_op:
        batch_op.drop_column('chunks_with_matches')
        batch_op.drop_column('chunks_analyzed')
        batch_op.drop_column('ai_score')

    # ### end Alembic commands ###
